UPDATE: Drupal Dev Portal 22.02.03.00

diff --git a/profiles/apigee/modules/contrib/nagios/nagios-plugin/check_drupal b/profiles/apigee/modules/contrib/nagios/nagios-plugin/check_drupal
--- a/profiles/apigee/modules/contrib/nagios/nagios-plugin/check_drupal
+++ b/profiles/apigee/modules/contrib/nagios/nagios-plugin/check_drupal
@@ -9,38 +9,51 @@
 ECHO="/bin/echo"
 GREP="/bin/egrep"
 RM="/bin/rm"
-CP="/bin/cp"
 WGET="/usr/bin/wget"
 SSL=/bin/false
 
-PROGNAME=`basename $0`
-PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
+PROGRAM_NAME=`basename "$0"`
+PROGRAM_PATH=`echo "$0" | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
+
+# shellcheck disable=SC2016
 REVISION=`echo '$Revision$' | sed -e 's/[^0-9.]//g'`
 
 temp=`mktemp`
 
-if [[ -e $PROGPATH/utils.sh ]]; then
-  . $PROGPATH/utils.sh
+if [[ -e $PROGRAM_PATH/utils.sh ]]; then
+  . "$PROGRAM_PATH/utils.sh"
 elif [[ -e /usr/lib/nagios/plugins/utils.sh ]]; then
   . /usr/lib/nagios/plugins/utils.sh
+elif [[ -e /usr/local/nagios/libexec/utils.sh ]]; then
+  . /usr/local/nagios/libexec/utils.sh
 else
-  echo 'Could not find nagios utils include file! Set PROGPATH on line 17 of the check_drupal script.'
+  echo 'Could not find nagios utils include file! Set PROGRAM_PATH on line 17 of the check_drupal script.'
   exit 1
 fi
 
 print_usage() {
-  $ECHO "Usage: $PROGNAME -U unique_id [ -H host_name ] [ -P path_to_nagios_status_page ] [ -t time_out_seconds ]"
-  $ECHO "Usage: $PROGNAME --help"
-  $ECHO "Usage: $PROGNAME --version"
+  $ECHO "Usage:"
+  $ECHO "  $PROGRAM_NAME -U unique_id [ -H host_name ] [ -S ] [ -P path_to_nagios_status_page ] [ -t time_out_seconds ] [ --http-user user --http-password password ]"
+  $ECHO "  $PROGRAM_NAME --help"
+  $ECHO "  $PROGRAM_NAME --version"
 }
 
 print_help() {
-  print_revision $PROGNAME $REVISION
+  print_revision "$PROGRAM_NAME" "$REVISION"
   $ECHO ""
   print_usage
   $ECHO ""
   $ECHO "Drupal monitoring plugin for Nagios"
   $ECHO ""
+  $ECHO "  -U   The secret user agent from the Nagios settings page within Drupal."
+  $ECHO "  -H   The domain or IP address under which this script should reach Drupal"
+  $ECHO "       with HTTPS . Default: 127.0.0.1."
+  $ECHO "  -S   Use HTTPS instead of HTTP."
+  $ECHO "  -P   The path of the status page without a leading slash. Default: nagios"
+  $ECHO "  -t   Seconds until wget should give up. Default: 2"
+  $ECHO ""
+  $ECHO "  --http-user user --http-password password"
+  $ECHO "       Not the Drupal login, but the HTTP-based basic, digest, or NTLM."
   support
 }
 
@@ -48,33 +61,25 @@ print_help() {
 # arguments have been supplied
 if [ $# -lt 1 ]; then
   print_usage
-  exit $STATE_UNKNOWN
+  exit "$STATE_UNKNOWN"
 fi
 
 # Grab the command line arguments
 
-exitstatus=$STATE_WARNING
+exit_status=$STATE_WARNING
 
 while test -n "$1"; do
   case "$1" in
-    --help)
+    --help|-h)
       print_help
-      exit $STATE_OK
+      exit "$STATE_OK"
       ;;
-    -h)
-      print_help
-      exit $STATE_OK
-      ;;
-    --version)
-      print_revision $PROGNAME $REVISION
-      exit $STATE_OK
-      ;;
-    -V)
-      print_revision $PROGNAME $REVISION
-      exit $STATE_OK
+    --version|-V)
+      print_revision "$PROGRAM_NAME" "$REVISION"
+      exit "$STATE_OK"
       ;;
     -H)
-      hostname=$2
+      host_name=$2
       shift
       ;;
     -U)
@@ -88,32 +93,35 @@ while test -n "$1"; do
     -S)
       SSL=/bin/true
       ;;
-    -t) 
+    -t)
       timeout=$2
       shift
       ;;
-    --http-user) 
-      httpuser=$2
+    --http-user)
+      http_user=$2
       shift
       ;;
-    --http-password) 
-      httppassword=$2
+    --http-password)
+      http_password=$2
       shift
       ;;
     *)
       $ECHO "Unknown argument: $1"
       print_usage
-      exit $STATE_UNKNOWN
+      exit "$STATE_UNKNOWN"
   esac
   shift
 done
 
-# Set a default for hostname
-if [ "$hostname" = "" ]; then
-  hostname=$NAGIOS_HOSTADDRESS
+# Set a default for host_name
+if [ "$host_name" = "" ]; then
+  host_name=$NAGIOS_HOSTADDRESS
+fi
+if [ "$host_name" = "" ]; then
+  host_name=127.0.0.1
 fi
 
-# Set a default for path
+# Set a default for "Nagios page path" - this must match your Drupal settings at /admin/config/system/nagios
 if [ "$path" = "" ]; then
   path="nagios"
 fi
@@ -130,63 +138,60 @@ fi
 
 
 if $SSL; then
-  CMD="$WGET --no-check-certificate -S -T $timeout -O - --http-user=$httpuser --http-password=$httppassword -U $unique_id https://$hostname/$path"
+  CMD="$WGET --no-check-certificate -S -T $timeout -O - --http-user=$http_user --http-password=$http_password -U $unique_id https://$host_name/$path"
 else
-  CMD="$WGET -S -T $timeout -O - -U $unique_id http://$hostname/$path"
+  CMD="$WGET -S -T $timeout -O - --http-user=$http_user --http-password=$http_password -U $unique_id http://$host_name/$path"
 fi
 
-$CMD > $temp 2>&1
+$CMD > "$temp" 2>&1
 RC=$?
 
-# When using http authentication wget always waits until it receives a 401 before sending the password. 
+# When using http authentication wget always waits until it receives a 401 before sending the password.
 # Therefore the first header should be stripped off
-if [ "$httppassword" != "" ]; then
-  temp2=`mktemp`
-  $GREP -v 'HTTP/1.1 401 Authorization Required' $temp > $temp2
-  $CP $temp2 $temp
-  $RM -f $temp2
+if [ "$http_password" != "" ]; then
+  ex -s +"g/HTTP\/1.1 401/d" -cwq "$temp"
 fi
 
-HTTP=`$GREP "HTTP/1" $temp`
+HTTP=`$GREP "HTTP/1" "$temp"`
 
 if [ "$RC" != 0 ]; then
-  $ECHO "wget error: $RC: when accessing $hostname/$path. HTTP: $HTTP"
-  $RM -f $temp
-  exit $STATE_UNKNOWN
+  $ECHO "wget error: $RC: when accessing $host_name/$path. HTTP: $HTTP"
+  $RM "$temp"
+  exit "$STATE_UNKNOWN"
 fi
 
 HTTP_CODE=`$ECHO "$HTTP" | awk '{print $2}'`
 if [ "$HTTP_CODE" != "200" ]; then
   $ECHO "HTTP returned an error code. HTTP: $HTTP"
-  $RM -f $temp
-  exit $STATE_UNKNOWN
+  $RM "$temp"
+  exit "$STATE_UNKNOWN"
 fi
 
-DATA="`$GREP "nagios=" $temp | sed -e 's/^.*nagios=//g'`"
+DATA="`$GREP "nagios=" "$temp" | sed -e 's/^.*nagios=//g'`"
 
 STATUS=`$ECHO "$DATA" | awk -F, '{print $1}'`
 
 case $STATUS in
 "OK")
-  exitstatus=$STATE_OK
+  exit_status=$STATE_OK
   ;;
 "WARNING")
-  exitstatus=$STATE_WARNING
+  exit_status=$STATE_WARNING
   ;;
 "UNAUTHORIZED")
-  exitstatus=$STATE_CRITICAL
+  exit_status=$STATE_CRITICAL
   ;;
 "CRITICAL")
-  exitstatus=$STATE_CRITICAL
+  exit_status=$STATE_CRITICAL
   ;;
 *)
-  exitstatus=$STATE_UNKNOWN
+  exit_status=$STATE_UNKNOWN
   ;;
 esac
 
 # Send the data
 $ECHO "DRUPAL $DATA"
 
-$RM -f $temp
+$RM "$temp"
 
-exit $exitstatus
+exit "$exit_status"
